TrixyWebapp/Controllers/StockSymbolController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;
using Repository.FyersWebSocketServices;
using Repository.IRepositories;
using Repository.Models;
using Repository.Repositories;
using System.Text;
using TrixyWebapp.Filters;

namespace TrixyWebapp.Controllers
{
    [Authorize]
    [SessionCheck]
    public class StockSymbolController : Controller
    {
        private readonly IRepository<StockSymbol> _stockSymbolRepository;
        private readonly IStockSymbolRepository _stockSymbol;
        private readonly IUserRepository _userRepository;
        private readonly IRepository<User> _masterRepository;
        private readonly FyersWebSocketService _fyersWebSocket;
        private readonly IWebStockRepository _webStockRepository;
        private readonly IErrorHandlingRepository _errorhandling;
        public StockSymbolController(IRepository<StockSymbol> stockSymbolRepository, 
            IStockSymbolRepository stockSymbol,
            IUserRepository userRepository,
            IRepository<User> masterRepository,
            FyersWebSocketService fyersWebSocketService,
            IWebStockRepository webStockRepository,
            IErrorHandlingRepository errorhandling)
        {
            _stockSymbolRepository = stockSymbolRepository;
            _stockSymbol = stockSymbol;
            _userRepository = userRepository;
            _masterRepository = masterRepository;
            _fyersWebSocket = fyersWebSocketService;
            _webStockRepository = webStockRepository;
            _errorhandling = errorhandling;
        }
        public async Task<IActionResult> Index()
        {
            var symbollist = await _stockSymbolRepository.GetAllAsync();
            return View(symbollist);

        }


        [HttpGet]
        public async Task<IActionResult> CreateSymbol(string? Id)
        {
            try
            {
                if (!string.IsNullOrEmpty(Id))
                {
                    var stockSymbol = await _stockSymbolRepository.GetByIdAsync(Id);
                    if (stockSymbol != null)
                    {
                        // Get the base URL dynamically
                        var origin = $"{Request.Scheme}://{Request.Host}{Request.PathBase}";

                        // Append the relative file path to get the full URL
                        stockSymbol.CompanyIconUrl = $"{origin}{stockSymbol.CompanyIconUrl}";

                        return View(stockSymbol); // Pass existing user data for editing
                    }
                }
                return View(new StockSymbol());

            }
            catch (Exception ex)
            {
                await _errorhandling.AddErrorHandling(ex, "StockSymbol/CreateSymbol");
                return View(new StockSymbol());
            }
           
        }
        [HttpGet]
        public async Task<bool> Validsymbol(string sym)
        {
            var isvalid= await _fyersWebSocket.IsSymbolValidAsync(sym);
            if (isvalid)
            {
                return true;
            }
            else {
                return false;
            }
        }
        [HttpPost]
        public async Task<IActionResult> CreateSymbol(StockSymbol stockSymbol)
        {
            try
            {
                if (!await Validsymbol(stockSymbol.Symbol))
                {
                    ViewBag.Errormessage = "Invalid symbol please try agin";
                    return View();
                }
                // Handle file upload
                if (stockSymbol.IconFile != null && stockSymbol.IconFile.Length > 0)
                {
                    var uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Uploads");
                    if (!Directory.Exists(uploadsFolder))
                    {
                        Directory.CreateDirectory(uploadsFolder);
                    }

                    string fileName = $"{Guid.NewGuid()}_{Path.GetFileName(stockSymbol.IconFile.FileName)}";
                    string filePath = Path.Combine(uploadsFolder, fileName);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        await stockSymbol.IconFile.CopyToAsync(stream);
                    }

                    // Store only the relative path in the database
                    stockSymbol.CompanyIconUrl = "/Uploads/" + fileName;
                }

                // **EDIT MODE: If ID exists, update the existing record**
                if (stockSymbol.Id.ToString() != null && stockSymbol.Id != ObjectId.Empty && stockSymbol.Id.ToString() != "000000000000000000000000")
                {
                    // await _userRepository.UpdateAsyncUserStocksLogo(stockSymbol.Symbol, stockSymbol.CompanyIconUrl);
                    var existingStock = await _stockSymbolRepository.GetByIdAsync(stockSymbol.Id.ToString());

                    if (existingStock != null)
                    {
                        // If no new file is uploaded, retain the old file path
                        if (string.IsNullOrEmpty(stockSymbol.CompanyIconUrl))
                        {
                            stockSymbol.CompanyIconUrl = existingStock.CompanyIconUrl;
                        }
                        
                        await _stockSymbolRepository.UpdateAsync(stockSymbol.Id.ToString(), stockSymbol);
                        await _fyersWebSocket.Connect();
                        return RedirectToAction("Index");
                    }
                }
                else
                {
                    // **CREATE MODE: Insert new record**
                    var existuser = await _stockSymbol.GetStockBySymbol(stockSymbol?.Symbol ?? "");
                    if (existuser == null)
                    {
                        var result = stockSymbol != null ? await _stockSymbolRepository.InsertAsync(stockSymbol) : 0;
                        if (result == 1)
                        {
                           await _fyersWebSocket.Connect();
                            return RedirectToAction("Index");
                        }
                        else
                        {
                            ViewBag.Errormessage = "Please try again";
                            return View();
                        }
                    }
                    else
                    {
                        ViewBag.Errormessage = "This symbol already exists.";
                        return View();
                    }
                }

                ViewBag.Errormessage = "Please try again";
                return View();
            }
            catch (Exception ex)
            {
                await _errorhandling.AddErrorHandling(ex, "StockSymbol/CreateSymbol");
                ViewBag.Errormessage = "Please try again";
                return View();
            }
           
        }

        [HttpGet]
        public async Task<IActionResult> GetStockList(string stocksym)
        {
            try
            {
                if (!string.IsNullOrEmpty(stocksym))
                {
                    var stocklist = await _stockSymbol.GetStocklistBySymbol(stocksym);
                    var stocklst = stocklist.Select(x => new
                    {
                        symbol = x.Symbol,
                        id = x.Id.ToString(),
                    });
                    return Json(stocklst);
                }
                else
                {
                    return Json(new List<Stocks>());
                }
            }
            catch (Exception ex)
            {
                await _errorhandling.AddErrorHandling(ex, "StockSymbol/GetStockList");
                return Json(new List<Stocks>());
            }
          
           
        }

        [HttpPost]
        public async Task<IActionResult> AddUserStock(string Symbol,string StockId)
        {
            try
            {
                var userId = HttpContext.Session.GetString("UserId");
                //string userId = Encoding.UTF8.GetString(userIdBytes);
                var user = userId != null ? await _masterRepository.GetByIdAsync(userId) : new User();
                if (!string.IsNullOrEmpty(StockId))
                {
                    var stockSymbol = await _stockSymbolRepository.GetByIdAsync(StockId);
                    if (stockSymbol != null)
                    {
                        if (user != null)
                        {
                            if (user.Stocks == null)
                            {
                                user.Stocks = new List<Stocks>();
                                user.Stocks.Add(new Stocks
                                {
                                    CompanyLogoUrl = stockSymbol.CompanyIconUrl,
                                    CompanyName = stockSymbol.CompanyName,
                                    IsActive = true,
                                    StockNotification = false,
                                    BuySellSignal = null,
                                    Symbol = stockSymbol.Symbol,
                                });
                            }
                            else
                            {
                                if (user.Stocks.Where(x => x.Symbol == stockSymbol.Symbol).FirstOrDefault() == null)
                                {
                                    user.Stocks.Add(new Stocks
                                    {
                                        CompanyLogoUrl = stockSymbol.CompanyIconUrl,
                                        CompanyName = stockSymbol.CompanyName,
                                        IsActive = true,
                                        StockNotification = false,
                                        BuySellSignal = null,

TrixyWebapp/Views/StockSymbol/CreateSymbol.cshtml
@using MongoDB.Bson
@model Repository.Models.StockSymbol
@{
    ViewData["Title"] = "CreateUser";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}

<div class="content-wrapper">
    <div class="container-full">
        <section class="content">
            <div class="row">
                <div class="col-xl-12 col-12">
                    <div class="box">
                        <div class="box-body">
                            <div>
                                @if (Model == null|| Model.Id.ToString() == null || Model.Id.ToString() == "000000000000000000000000")
                                {
                                    <h1>Create Symbol</h1>
                                }
                                else
                                {
                                    <h1>Update Symbol</h1>
                                }

                                <hr />
                                <div class="row">
                                    <div class="col-md-4">
                                        <form asp-action="CreateSymbol" method="post" id="CreateSymbolform" enctype="multipart/form-data">
                                            @if (ViewBag.Errormessage != null)
                                            {
                                                <div class="alert alert-danger text-center">
                                                    @ViewBag.Errormessage.ToString()
                                                </div>
                                            }

                                            <input name="Id" type="hidden" value="@Model?.Id" />

                                            <div class="form-group">
                                                <label class="control-label">Symbol</label>
                                                <input name="Symbol" value="@Model?.Symbol" class="form-control" required />
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label">Company Name</label>
                                                <input name="CompanyName" class="form-control" value="@Model?.CompanyName" required />
                                            </div>

                                            <div class="form-group">
                                                <label class="control-label">Upload Icon</label>
                                                <input name="IconFile" id="IconFile" type="file" class="form-control"/>

                                                <!-- Show the existing image if available (Edit mode) -->
                                                @if (!string.IsNullOrEmpty(Model?.CompanyIconUrl))
                                                {
                                                    <div class="mt-2">
                                                        <label>Current Icon:</label>
                                                        <br />
                                                        <img src="@Model.CompanyIconUrl" alt="Current Icon" width="100" height="100" />
                                                    </div>
                                                }
                                            </div>

                                            <div class="form-group">
                                                @if (Model?.Id == null || Model?.Id.ToString() == "000000000000000000000000" || Model?.Id == ObjectId.Empty)
                                                {
                                                    <input type="submit" value="Create" class="btn btn-primary mt-10" />
                                                }
                                                else{
                                                    <input type="submit" value="Update" class="btn btn-primary mt-10" />
                                                }
                                                @* <input type="submit" value="@((Model?.Id == null && Model.Id.ToString() == "000000000000000000000000") ? "Create" : "Update")" class="btn btn-primary mt-10" /> *@
                                                <a href="/StockSymbol/Index" class="btn btn-danger mt-10">Back to List</a>
                                            </div>
                                        </form>

                                    </div>
                                </div>
                            </div>


                        </div>
                    </div>
                </div>
            </div>


        </section>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

TrixyWebapp/Views/StockSymbol/Index.cshtml
@model IEnumerable<Repository.Models.StockSymbol>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_Layout.cshtml";
}
<style>

    .bootbox .modal-body .close {
        margin: 0rem 0rem 0rem auto;
        font-size: 1.5rem;
        font-weight: 700;
        color: #000;
        opacity: 0.5;
        float: right;
    }
</style>
<h1>Index</h1>
<div class="content-wrapper">
    <div class="container-full">
        <section class="content">
            <div class="col-xl-12 col-12">
                <div class="box">
                   
                    <p>
                        <a href="/StockSymbol/CreateSymbol" class="btn btn-danger mt-10" style="float:right;    margin-right: 10px;">Create New</a>
                    </p>
                    <div class="box-body">

                        <div class="table-responsive customize-responsive-table stocksym-tables">
                            <table id="stocksym" class="table mt-0 table-hover no-wrap" data-page-size="10">
                                <thead>
                                    <tr>
                                        <th>
                                            Symbol
                                        </th>
                                        <th>
                                            Company Name
                                        </th>
                                       
                                        <th>
                                            Status
                                        </th>
                                        <th>
                                            Action
                                        </th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model != null && Model.Any())
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.Symbol)
                                                </td>
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.CompanyName)
                                                </td>
                                              
                                                <td>
                                                    @Html.DisplayFor(modelItem => item.StatusText)
                                                </td>
                                                <td>
                                                    <a href="@Url.Action("CreateSymbol","StockSymbol",new{id = item.Id.ToString()})"
                                                       class="waves-effect waves-circle btn-circle btn btn-info  btn-xs"
                                                       data-bs-toggle="tooltip"
                                                       data-bs-original-title="Update">
                                                        <i class="ti-pencil-alt" aria-hidden="true"></i>
                                                    </a>
                                                  
                                                    <a href="@Url.Action("DeleteSymbol","StockSymbol",new{id = item.Id.ToString()})"
                                                       class="waves-effect waves-circle btn-circle btn btn-info  btn-xs btn-danger delete-stockSymbol" data-Id="@item.Id"
                                                       data-url="@Url.Action("DeleteSymbol", "StockSymbol", new { id = item.Id.ToString() })"
                                                       data-bs-toggle="tooltip"
                                                       data-bs-original-title="Delete">
                                                        <i class="ti-trash" aria-hidden="true"></i>
                                                    </a>
                                                 
                                                </td>
                                            </tr>
                                        }
                                    }

                                </tbody>
                            </table>

                        </div>

                    </div>
                </div>
            </div>

        </section>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

<!-- Bootstrap JS (required for $.fn.modal used by Bootbox) -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/bootbox.js/4.4.0/bootbox.min.js"></script>

<link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" rel="stylesheet" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
<script>
    $(document).on('click', '.delete-stockSymbol', function (e) {
        e.preventDefault(); // Stop default anchor navigation
        debugger
        const url = $(this).data('url');

        bootbox.confirm({
            message: "Are you sure you want to remove this Stock Symbol?",
            buttons: {
                confirm: {
                    label: 'Yes',
                    className: 'btn-danger'
                },
                cancel: {
                    label: 'Cancel',
                    className: 'btn-secondary'
                }
            },
            callback: function (result) {
                if (result) {
                        $.post(url, function (data) {
                        if (data) {
                            toastr.success("Stock Symbol deleted successfully");
                            window.location.reload(); // or toastr, etc.
                        } else {
                             toastr.success("Failed to delete.");

                        }
                    });
                    // window.location.href = url;
                }
            }
        });
    });
</script>